### PR TITLE
Add mode option to return results as array.

### PR DESCRIPTION
**Pull request by AndersDJohnson**

### CODE REVIEW

**Comment by terinjokes** [comment]
Please don't save the results if you're not in "array" mode.

Thanks for the PRs, I'm away from my phone but will review them all soon.

**Comment by AndersDJohnson** [comment]
@terinjokes Force pushed change to not push result if not in "array" mode. I still initialize the results array in the private map either way, do you mind?

Also, feel free to suggest an alternate way of specifying this option besides `mode: 'array'`.

**Comment by terinjokes** [comment]
I'll look at other languages and see what they call this.

**Comment by terinjokes** [comment]
Thanks for the PR @adjohnson916. Just wondering, what's the use case for this?

---

So I don't forget, this is a "scan". This library should probably be called "promise-reduce", but I nit-pick in hindsight.

**Comment by AndersDJohnson** [comment]
@terinjokes For business logic reasons, I need to execute an array of promises in series, not in parallel, but I need to capture the results of each promise, not just the result of the last.

**Comment by terinjokes** [comment]
@adjohnson916 Do you mind reopening this as an issue?

**Comment by AndersDJohnson** [comment]
Re-opened as issue #6.

**Pull request closed without merging**
